# Generated by Django 6.1.1 on 2026-10-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
