# Generated by Django 6.1.1 on 2026-10-05 10:16

import resu_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resu_app', '0002_alter_resumodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumodel',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[resu_app.models.validate_pdf_extension]),
        ),
        migrations.AlterField(
            model_name='resumodel',
            name='transcript',
            field=models.FileField(upload_to='transcript/', validators=[resu_app.models.validate_pdf_extension]),
        ),
    ]
